### POST to /
POST http://localhost:8080/courses
Content-Type: application/json

{
  "name": "Curso de Node",
  "description": "Curso de Node avançado",
  "workload": 120
}


### GET to /
GET http://localhost:8080/courses
Content-Type: application/json



### GET to /ID
GET http://localhost:8080/courses/?id=0fb05b0f-70bf-44ba-bff9-801edd5f72b3
Content-Type: application/json
