### POST to /
POST http://localhost:8080/courses
Content-Type: application/json

{
  "name": "Curso de java",
  "description": "Curso de java avançado",
  "workload": 100
}


### GET to /
GET http://localhost:8080/courses
Content-Type: application/json
