### POST to /
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Mx Keys",
  "price": 320.00
}


### GET to /
GET http://localhost:8080/products
Content-Type: application/json


### GET to /
GET http://localhost:8080/products/?id=b41fff09-1ffe-46cf-b61a-1ccbc1eceac0
Content-Type: application/json
