### POST to /
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Mx Keys",
  "price": 320.00
}


### GET to /
GET http://localhost:8080/products
Content-Type: application/json
