### POST to /
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Mx Keys Mini",
  "price": 420.00
}


### GET to /
GET http://localhost:8080/products
Content-Type: application/json
